# === Pybullet Envs ===

# Tuned
HalfCheetahBulletEnv-v0: &pybullet-defaults
  normalize: true
  n_envs: 2
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3

# === Mujoco Envs ===

# Tuned
HalfCheetah-v5: &mujoco-defaults
  <<: *pybullet-defaults
  target_kl: 0.04
  ent_coef: .00005

# Tuned
Hopper-v5:
  <<: *mujoco-defaults
  ent_coef: 0.0003

# Tuned
Walker2d-v5:
  <<: *mujoco-defaults
  ent_coef: 
  
Humanoid-v5:
  <<: *mujoco-defaults
  ent_coef: 

HumanoidStandup-v5:
  <<: *mujoco-defaults
  ent_coef: 

# Tuned
Swimmer-v5:
  <<: *mujoco-defaults
  gamma: 0.9999
  ent_coef: 0.03
