# Source: RL Baselines3 Zoo hyperparams/trpo.yml (Nov 2024 update for MuJoCo v4; compatible with v5 due to minor changes)
# Tuned
HalfCheetah-v5: &defaults
  normalize: true
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: 0.001
  target_kl: 0.01  # max_kl in TRPO
  net_arch: small  # [64, 64]
  activation_fn: tanh

# Source: RL Baselines3 Zoo hyperparams/trpo.yml (tuned for Hopper-v4; strong performance on locomotion tasks)
# Tuned
Hopper-v5:
  <<: *defaults

# Source: RL Baselines3 Zoo hyperparams/trpo.yml (tuned for Walker2d-v4; strong performance on locomotion tasks)
# Tuned
Walker2d-v5:
  <<: *defaults

# Source: RL Baselines3 Zoo hyperparams/trpo.yml (tuned for Humanoid-v4; achieves good balance in 2M timesteps)
Humanoid-v5:
  <<: *defaults
  net_arch: medium  # Approx [128, 128]; adapted from original TRPO paper for complex envs

# Source: Adapted from RL Baselines3 Zoo Humanoid-v4 (similar body model; no specific tune, but performs well on standup tasks with medium arch)
HumanoidStandup-v5:
  <<: *defaults
  net_arch: medium  # Approx [128, 128]; adapted from original TRPO paper for complex envs

# Source: RL Baselines3 Zoo hyperparams/trpo.yml (tuned for Swimmer-v4; gamma override for long-horizon)
# Tuned
Swimmer-v5:
  <<: *defaults
  gamma: 0.9999