# Tuned
HalfCheetah-v5: &defaults
  normalize: true
  batch_size: 512
  n_steps: 2048
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 5
  cg_damping: 0.1
  n_critic_updates: 10
  learning_rate: 0.035
  target_kl: 0.1
  net_arch: small
  activation_fn: tanh
  ent_coef: 0.0005

# Tuned
Hopper-v5:
  <<: *defaults
  ent_coef: 0.0003

# Tuned
Walker2d-v5:
  <<: *defaults
  ent_coef: 

# Tuned
Humanoid-v5:
  <<: *defaults
  net_arch: medium  # Approx [128, 128]; adapted from original TRPO paper for complex envs
  ent_coef: 0.0005

# Tuned
HumanoidStandup-v5:
  <<: *defaults
  net_arch: medium  # Approx [128, 128]; adapted from original TRPO paper for complex envs
  ent_coef: 0.0002

# Tuned
Swimmer-v5:
  <<: *defaults
  gamma: 0.9999
  ent_coef: 0.03

