# === Pybullet Envs ===

# Tuned
HalfCheetahBulletEnv-v0: &pybullet-defaults
  normalize: true
  n_envs: 2
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3

# === Mujoco Envs ===

Ant-v4: &mujoco-defaults
  <<: *pybullet-defaults
  n_timesteps: !!float 1e6
  
# Tuned
HalfCheetah-v5:
  <<: *mujoco-defaults
  target_kl: 0.04

# Tuned
Hopper-v5:
  <<: *mujoco-defaults

# Tuned
Walker2d-v5:
  <<: *mujoco-defaults

Humanoid-v5:
  <<: *mujoco-defaults

HumanoidStandup-v5:
  <<: *mujoco-defaults

# Tuned
Swimmer-v5:
  <<: *mujoco-defaults
  gamma: 0.9999

